# -*- coding: utf-8 -*-
"""charger_1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvey4u0wPIk4ds1frf6DnRnit6VrXe12
"""

import numpy as np
from matplotlib import pyplot as plt
import os

A = 12
f = 50
t = np.linspace(0, 2/f, 1000)
plt.plot(t, np.abs(A*np.sin(2*np.pi*f*t)))
plt.grid()
plt.xlabel('t')
plt.ylabel('x(t)')